routes/admin.php
<?php
namespace  App\Http\Controllers\Dashboard;
use App\Http\Controllers\Dashboard\Subscriptions\PlanController;
use App\Http\Controllers\Dashboard\Subscriptions\SubscriptionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});



Route::group(['as'=>'admin.','prefix'=>'dashboard/admin','middleware' => 'auth:Admin'],function (){
    Route::get('/',[IndexController::class,'index'])->name('index');
    Route::get('print/orders/{order}',[OrderController::class,'print'])->name('order.print');
    Route::resources([
        'admins'=>AdminController::class,
        'families'=>FamilyController::class,
        'categories'=>CategoryController::class,
        'sub-categories'=>SubCategoryController::class,
        'products'=>ProductController::class,
        'product-colors'=>ProductColorController::class,
        'product-sizes'=>ProductSizeController::class,
        'deliveries'=>DeliveryController::class,
        'banners'=>BannerController::class,
        'coupons'=>CouponController::class,
        'orders'=>OrderController::class,
        'users'=>UserController::class,
        'cities'=>CityController::class,
        'contacts'=>ContactController::class,
        'notifications'=>NotificationController::class,
        'roles'=>RoleController::class,
        'plans'=>PlanController::class,
        'settings'=>SettingsController::class,
        'supported-cities'=>SupportedCityController::class
    ]);
    Route::put('delivery/assign/{cart}',[DeliveryController::class,'assignOrder'])->name('delivery.assign');
    Route::get('login/{family}',[FamilyController::class,'login'])->name('families.login');
    Route::post('subscription/{family}/{type}',[SubscriptionController::class,'subscription'])->name('subscription');
    Route::post('subscription/{family}',[SubscriptionController::class,'updateSubscription'])->name('update.subscription');
    Route::get('gallery-destroy/{media}',[ProductController::class,'destroyGallery'])->name('gallery.destroy');
    Route::get('nearly-ended-subscriptions',[SubscriptionController::class,'nearlyEnded'])->name('nearlyEnded');
    Route::get('roles/{role}',[RoleController::class,'changeStatus'])->name('active.role');
    Route::get('product-size-default/{product}/{productSize}',[ProductSizeController::class,'toggleDefault'])->name('product-size-toggle');
    Route::get('rate/product',[RateController::class,'product'])->name('rate.product');
    Route::get('rate/family',[RateController::class,'family'])->name('rate.family');
    Route::get('orders/{order}/{status}',[OrderController::class,'changeStatus'])->name('order.change.status');
    Route::view('tracking','dashboard.deliveries.tracking')->name('deliveries.tracking');
});

routes/web.php
<?php

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/','dashboard.layout.login' );
//Route::view('/','landing' );

Route::get('add_family', [HomeController::class,'index'])->name('web.add_family');
Route::post('store_family', [HomeController::class,'storeFamily'])->name('web.store_family');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Http/Controllers/Api/Family/AuthController.php
<?php

namespace App\Http\Controllers\Api\Family;

use App\Http\Controllers\Controller;
use App\Http\Resources\FamilyResource;
use Illuminate\Http\Request;
use JWTAuth;
use responder;

class AuthController extends Controller
{
    private $auth;
    public function __construct()
    {
        $this->auth=auth('api_family');
    }

    public function login( Request $request)
    {
        $request->validate([
            "email" => 'required|exists:families,email',
            'password' => 'required',
            'token'=>'required|string',
            'device'=>'required|in:android,ios',
        ]);
        $credentials = request(['email', 'password']);
        $attemp=$this->auth->attempt($credentials);
        if (!$attemp) {
            return responder::error('خطأ في بيانات الدخول !');
        }
        $user=$this->auth->user();
        $user->logout = $user->devices()->firstOrCreate($request->only('token', 'device'))->id;
        $user->token = JWTAuth::fromUser($user);
        return responder::success(new FamilyResource($user));
    }

    public function profile()
    {
        $user = $this->auth->user();
        $user->token = JWTAuth::getToken()->get();
        return responder::success(new FamilyResource($user));
    }

    public function updateProfile(Request $request)
    {
        $user=$this->auth->user();
        $id=$user->id;
        $rules = [
            'phone' => 'sometimes|numeric|unique:families,phone,' . $id,
            'password' => 'sometimes',
            'name' => 'sometimes|unique:users,name,' . $id,
            'image' => 'sometimes|image',
            'bio'=>'sometimes|string',
            'lat'=>'required_with:lng',
            'lng'=>'required_with:lat',
            'address'=>'sometimes|string',
            'city_id'=>'sometimes|exists:cities,id',
            'is_online'=>'sometimes|boolean',
            'order_type'=>'sometimes'
        ];
        $validated=$request->validate($rules);
        $user->update($validated);
        $user->token = JWTAuth::fromUser($user);

        return responder::success(new FamilyResource($user));
    }

    public function logout(Request $request)
    {
        $request->validate([
            'logout'=>'required|exists:devices,id'
        ]);
        $user=$this->auth->user();
        $user->devices()->where('devices.id',$request['logout'])->delete();
        $this->auth->logout();
        return responder::success('تم تسجيل الخروج بنجاح !');
    }

  /*  public function confirmation(Request $request, $role)
    {
        $request->validate([
            'phone' => 'required|exists:' . $this->roleToTableName($role) . ',phone',
            'code' => 'required'
        ]);
        $user = $this->getModel($role)::where('phone', $request->phone)->where('confirmation_code', $request->code);
        if (!$user->exists()) {
            return $this->apiResponse(null, __('wrong code'));
        }
        $user->first()->update([
            'is_confirmed' => 1,
            'confirmed_at' => now()->toDateTimeString(),
            'confirmation_code' => Str::random(15)
        ]);


        return $this->apiResponse(__('user confirmed successfully'));

    }

    public function forget_password(Request $request, $role)
    {
        $request->validate([
            'phone' => 'required|exists:' . $this->roleToTableName($role) . ',phone',
        ]);
        $user = $this->getModel($role)::where('phone', $request->phone);
        $user->first()->update([
            'reset_code' => 1234,
            'reset_at' => now()->toDateTimeString()
        ]);

        return $this->apiResponse(__('reset code sent successfully !'));
    }

    public function check_code(Request $request, $role)
    {
        $request->validate([
            'phone' => 'required|exists:' . $this->roleToTableName($role) . ',phone',
            'code' => 'required'
        ]);
        $user = $this->getModel($role)::where('phone', $request->phone)->where('reset_code', $request->code)->exists();


        return $this->apiResponse($user);
    }

    public function reset_code(Request $request, $role)
    {
        $request->validate([
            'phone' => 'required|exists:' . $this->roleToTableName($role) . ',phone',
            'code' => 'required',
            'password' => 'required'
        ]);
        $user = $this->getModel($role)::where('phone', $request->phone)->where('reset_code', $request->code);
        if (!$user->exists()) return $this->apiResponse(__('wrong reset code '));

        $user->update([
            'password' => bcrypt($request->password),
            'reset_code' => Str::random(15)
        ]);

        return $this->apiResponse(__('reset password completed !'));
    }*/
}

app/Http/Controllers/Api/Family/CartController.php
<?php

namespace App\Http\Controllers\Api\Family;

use App\Http\Controllers\Controller;
use App\Http\Requests\Family\UpdateCartRequest;
use App\Http\Resources\BaseCollection;
use App\Http\Resources\Cart\CartResource;
use App\Models\Cart;
use App\Notifications\OrderStatusChanged;
use App\Traits\FireBase;
use responder;
use function request;

class CartController extends Controller
{

    public function index()
    {
        $orders=Cart::query();
        $orders->where('family_id',auth()->id());
        if (request()->has('status')){
            $orders->whereIn('status', request('status'));
        }
        return responder::success(new BaseCollection($orders->with('user','logs','family','address','deliveries','items','items.color','items.size','items.product','requests')->orderByDesc('created_at')->paginate(15),CartResource::class));
    }

    public function show(Cart $cart)
    {
        return responder::success(new CartResource($cart));
    }

    public function update(UpdateCartRequest $request,Cart $cart)
    {

        $cart->update($request->validated());
        $cart->user->notify(new OrderStatusChanged($cart));
        if ($request['status']=='wait_for_delivery'){
            FireBase::sendFCMTopic('/topics/city-'.$cart->family->city_id,[
                'title'=>'تطبيق من البيت للبيت',
                'body'=>'هناك طلب جديد في منطقتك',
                'order_id'=>$cart->id,
                'type'=>'newOrder'
            ]);
        }
        return responder::success('تم تعديل حالة الطلب بنجاح !');
    }

}

app/Http/Controllers/Dashboard/ContactController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Contact;

class ContactController extends Controller
{
    //

    public function index()
    {
        return view('dashboard.contact.index')->with('contacts',Contact::orderByDesc('created_at')->get());
    }
}

app/Http/Controllers/Dashboard/FamilyController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Family;
use DB;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\View\View;
use Rinvex\Subscriptions\Models\Plan;

class FamilyController extends Controller
{

    public function login(Family $family)
    {
        auth('family')->login($family);
        return redirect()->route('family.profile.index');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index(Request $request)
    {
        $users = Family::with('city', 'rates')->withSum(['carts' => function ($q) {
            $q->whereIn('status', ['finished', 'force_finish']);
        }], 'grand_total')->withCount('carts')->withAvg('rates', 'value')->latest()->get();
        return view('dashboard.family.index', [
            'users' => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('dashboard.family.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'name' => 'required|string',
            'password' => 'required|confirmed',
            'email' => 'sometimes|email|unique:families,email',
            'phone' => 'required|numeric|unique:families,phone',
            'image' => 'required|image',
            'address' => 'required|string',
            'lat' => 'required|numeric',
            'lng' => 'required|numeric',
            'bio' => 'required|string',
            'city_id' => 'required|exists:cities,id',
            'order' => 'nullable|sometimes|integer|min:0',
            'order_until'=>'sometimes|nullable|date|after:today',
            'plan_id' => 'required|exists:plans,id',
            'start_subscription_at'=>'required_with:plan_id|date|date_format:Y-m-d',
            'order_type'=>'required',
            'is_active'=>'required|boolean'

        ]);
        DB::beginTransaction();
        $validator['creator_name']=auth()->user()->name;
        $user = Family::create($validator);
        $user->newSubscription('main', Plan::find($request['plan_id']),$request['start_subscription_at']);
        $user->cities()->sync($request['cities']);
        DB::commit();
        toast('تم اضافة الاسرة  بنجاح !', 'success');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show(Family $family)
    {
        $plans = Plan::all()->mapWithKeys(function ($q) {
            return [$q['id'] => $q['name']];
        });
        return \view('dashboard.family.show')->with(['plans' => $plans, 'user' => $family, 'subscription' => $family->subscriptions()->latest()->first()]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Family $family
     * @return Factory|View
     */
    public function edit(Family $family)
    {
        return view('dashboard.family.edit', ['user' => $family]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Family $family
     * @return RedirectResponse
     */
    public function update(Request $request, Family $family)
    {
        $validator = $request->validate([
            'name' => 'required|string',
            'password' => 'nullable|confirmed',
            'email' => 'required|email|unique:families,email,' . $family->id,
            'phone' => 'required|numeric|unique:families,phone,' . $family->id,
            'image' => 'sometimes|nullable|image',
            'address' => 'required|string',
            'lat' => 'required|numeric',
            'lng' => 'required|numeric',
            'bio' => 'required|string',
            'city_id' => 'required|exists:cities,id',
            'order' => 'nullable|sometimes|integer|min:0',
            'plan_id' => 'sometimes|exists:plans,id',
            'start_subscription_at'=>'required_with:plan_id|date|date_format:Y-m-d',
            'order_until'=>'sometimes|nullable|date|after:today',
            'order_type'=>'required',
            'is_active'=>'required|boolean'
        ]);
        $validator = array_filter($validator, function ($value) {
            return !is_null($value) && $value !== '';
        });
        $family->update($validator);

        toast('تم تعديل الاسرة  بنجاح !', 'success');
        return redirect()->route('admin.families.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Admin $admin
     * @return RedirectResponse
     * @throws Exception
     */
    public function destroy(Family $family)
    {
        $family->delete();
        toast('تم حذف الاسرة بنجاح !', 'success');
        return back();
    }
}

app/Http/Controllers/Dashboard/IndexController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Cart;
use App\Models\Family;
use DB;
use Illuminate\Http\Request;

class IndexController extends Controller
{
    public function index(Request $request)
    {
        $from = now()->firstOfMonth();
        $to = now()->endOfMonth();
        if ($request->from and $request->to) {
            $from = $request->from;
            $to = $request->to;
        }
        $locations= DB::table('carts')->join('addresses','addresses.id','=','carts.address_id')->select(['addresses.lat','addresses.lng'])->get()->toArray();


        $data = [
            'new_families' => Family::dateFilter($from, $to)->count(),
            'families' => Family::count(),
            'carts' => Cart::dateFilter($from, $to)->count(),
            'carts_finished' => Cart::whereStatus('finished')->dateFilter($from, $to)->count(),
            'carts_pending' => Cart::whereStatus('pending')->dateFilter($from, $to)->count(),
            'carts_total' => Cart::whereStatus('finished')->dateFilter($from, $to)->sum('grand_total'),
            'carts_delivery' => Cart::whereStatus('finished')->dateFilter($from, $to)->sum('delivery_cost'),
            'pending_carts' => Cart::whereStatus('pending')->with('user', 'family')->get(),
            'going_carts' => Cart::whereIn('status', ['accepted', 'wait_for_delivery', 'on_deliver'])->with('user', 'family')->get(),
            'carts_in_days' => Cart::selectRaw('count(id) as carts , date(created_at) as created_at_date')->groupBy('created_at_date')->get()->toArray(),
            'carts_locations' => $locations


        ];
        return view('dashboard.layout.main', $data);
    }
}

resources/views/dashboard/family/add.blade.php
@extends('dashboard.layout.app')

@section('title')
إضافة  اسرة
@endsection
@section('header')

@endsection

@section('content')

<!-- Basic Validation -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card ">
      <div class="header">
        <h2>إضافة  اسرة</h2>
        <ul class="header-dropdown m-r--5">
            <a href="{{route('admin.families.index')}}">   <button class="btn btn-danger">كل الاسر </button></a>
</ul>
      </div>
      <div class="body">
          {!!Form::open( ['route' => 'admin.families.store' ,'class'=>'form', 'method' => 'Post','files'=>true]) !!}
            @include('dashboard.family.form')
          {!!Form::close() !!}
      </div>
    </div>
  </div>
</div>
<!-- #END# Basic Validation -->
@endsection

@section('footer')

@endsection

resources/views/dashboard/family/edit.blade.php
@extends('dashboard.layout.app')

@section('title')
تعديل الاسرة
{{ $user->name }}
@endsection
@section('content')
<!-- Basic Validation -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card ">
      <div class="header">
        <h2>تعديل الاسرة       {{ $user->name }}</h2>
        <ul class="header-dropdown m-r--5">
            <a href="{{route('admin.families.index')}}">   <button class="btn btn-danger">كل الاسر</button></a>
         </ul>
      </div>
      <div class="body">
        {!!Form::model($user , ['route' => ['admin.families.update' , $user->id] , 'method' => 'PATCH','files'=>true]) !!}
          @include('dashboard.family.form')
          {!!Form::close() !!}
      </div>
    </div>
  </div>
</div>
<!-- #END# Basic Validation -->
@endsection

resources/views/dashboard/family/form.blade.php
<div class="row">

    <x-text name="name" title="الاسم"></x-text>
    <x-text name="email" title="البريد الالكتروني"></x-text>
    <x-password/>
    <x-text name="phone" title="رقم الهاتف"></x-text>
    <div class="col-md-6">
        <x-file name="image" title="الصورة الشخصية"/>
    </div>
    <x-number name="order" title="الترتيب"></x-number>
    <div class="col-md-6">
        <div class="form-group ">
            <label class="form-label">تاريخ انتهاء الترتيب</label>
            {!! Form::date('order_until',null,['class'=>'form-control','placeholder'=>'تاريخ انتهاء الترتيب'])!!}
            <div class="form-line">
            </div>
        </div>
    </div>
    <x-text name="address" title="العنوان"></x-text>


    <x-select title="المدينة" name="city_id" :items="cities()"></x-select>


    @if(!isset($user) or !$user->subscriptions()->exists())
        <x-plans :model="@$user"></x-plans>
    @endif

    {{--    <x-select title="نوع الطلب" name="order_type" :items="['عند الطلب','تسليم فوري']" :float="false"></x-select>--}}
    <x-select title="نوع الطلب" name="order_type"
              :items="['on_delivery' => 'عند الطلب' ,'immediate_delivery' => 'تسليم فوري']"
              :float="false"></x-select>

    <div class="form-group col-md-12 ">
        <label class="form-label">موقعها</label>
        {!! Form::text("lat",isset($user) && $user->lat ? null : 31.95080183791635,['id'=>'lat'])!!}
        {!! Form::text("lng",isset($user) && $user->lng ? null : 35.91058039003076,['id'=>'lng'])!!}
        <div id="map" style="height: 400px"></div>
    </div>
    <x-text-area name="bio" title="نبذة عن الاسرة"/>
    <x-select title="التفعيل" name="is_active" :items="['غير مفعل','مفعل']"></x-select>

</div>

<button class="btn btn-primary waves-effect" type="submit">حفظ</button>


@push('scripts')
    {!! Html::script('_dashboard/js/map.js') !!}
    <script
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAV3ZKirEWJIMW8T4SWoK9rXd7VThciUtw&callback=initMap&libraries=&v=weekly"></script>
@endpush

resources/views/dashboard/family/index.blade.php
@extends('dashboard.layout.app')

@section('title')
كل الاسر
@endsection
@section('header')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css
" />
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.5/css/responsive.dataTables.min.css
" />
@endsection
@section('content')
<!-- Exportable Table -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card ">
            <div class="header">
                <h2>
                    كل الاسر المنتجة
                </h2>
                <ul class="header-dropdown m-r--5">
                    <a href="{{route('admin.families.create')}}"> <button class="btn btn-success">إضافة اسرة جديدة</button></a>
                </ul>
            </div>
            <div class="body">
                <table class="table display nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>الإسم</th>
                            <th>البريد الإلكتروني</th>
                            <th>الموبيل</th>
                            <th>الصورة</th>
                            <th>المدينة</th>
                            <th>التقييم</th>
                            <th>تاريخ انتهاء الاشتراك</th>
                            <th>منشئ الاسرة</th>
                            <th>الترتيب</th>
                            <th>عدد الطلبات</th>
                            <th>اجمالي المبيعات</th>
                            <th>العمليات</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $key=>$user)
                        <tr>
                            <td>{{++$key}}</td>
                            <td>{{$user->name}}</td>
                            <td>{{$user->email}}</td>
                            <td>{{$user->phone}}</td>
                            <td><a href="{{$user->image}}" target="_blank"><img src="{{$user->image}}" class="img-responsive img-thumbnail"   style="width:75px; height: 75px" alt=""></a></td>
                            <td>{{optional($user->city)->name}}</td>
                            <td>{{$user->rates_avg_value}}</td>
                            <td>{{$user->subscribe_until}}</td>
                            <td>{{$user->creator_name}}</td>
                            <td>{{$user->order}}</td>
                            <td>{{$user->carts_count}}</td>
                            <td>{{$user->carts_sum_grand_total}}</td>

                            <td>
                                <a href="{{route('admin.families.login',$user)}}" target="_blank" class="btn btn-info btn-circle" data-original-title="تسجيل دخول">
                                    <i style="padding-top:5px;padding-left: 6px;" class="fa fa-key"></i>
                                </a>
                                <a href="{{route('admin.families.show',$user)}}" class="btn btn-info btn-circle" data-original-title="عرض">
                                    <i style="padding-top:5px;padding-left: 6px;" class="fa fa-eye"></i>
                                </a>
                                <a href="{{route('admin.families.edit',$user->id)}}" class="btn btn-info btn-circle" data-original-title="تعديل">
                                    <i style="padding-top:5px;padding-left: 6px;" class="fa fa-pencil"></i>
                                </a>
                                <a href="#" onclick="Delete({{$user->id}})" data-toggle="tooltip" data-original-title="حذف" class="btn btn-danger btn-circle">
                                    <i style="padding-top: 5px;padding-left: 4px;" class="fa fa-trash-o"></i>
                                </a>
                                {!!Form::open( ['route' => ['admin.families.destroy',$user->id] ,'id'=>'delete-form'.$user->id, 'method' => 'Delete']) !!}
                                {!!Form::close() !!}
                            </td>

                        </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- #END# Exportable Table -->

@endsection

@push('scripts')
<script>
    function Delete(id) {
        var item_id = id;
        // console.log(item_id);
        Swal.fire({
            title: "هل أنت متأكد ",
            text: "هل تريد حذف هذا العضو ؟",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'موافق !',
            cancelButtonText:'الغاء'
        }).then((result) => {
            if (result.value) {
                document.getElementById('delete-form' + item_id).submit();
            }else{
                Swal.fire(
                    'تم الالغاء!',
                    'تم الغاء الحذف بنجاح !',
                    'success'
                )
            }
        });

    }

</script>
@include('dashboard.layout.datatable-scripts')
@endpush

resources/views/dashboard/family/nearly-ended.blade.php
@extends('dashboard.layout.app')

@section('title')
الاشتراكات التي قاربت علي الإنتهاء
@endsection
@section('header')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css
" />
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.5/css/responsive.dataTables.min.css
" />
@endsection
@section('content')
<!-- Exportable Table -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card ">
            <div class="header">
                <h2>
                    الاشتراكات التي قاربت علي الإنتهاء
                </h2>
            </div>
            <div class="body">
                <table class="table display nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>الإسم</th>
                            <th>البريد الإلكتروني</th>
                            <th>الموبيل</th>
                            <th>الصورة</th>
                            <th>المدينة</th>
                            <th>التقييم</th>
                            <th>تاريخ التسجيل</th>
                            <th>الترتيب</th>
                            <th>العمليات</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($subscriptions as $key=>$subscription)
                        <tr>
                            <td>{{++$key}}</td>
                            <td>{{$subscription->user->name}}</td>
                            <td>{{$subscription->user->email}}</td>
                            <td>{{$subscription->user->phone}}</td>
                            <td><a href="{{$subscription->user->image}}" target="_blank"><img src="{{$subscription->user->image}}" class="img-responsive img-thumbnail"   style="width:75px; height: 75px" alt=""></a></td>
                            <td>{{@$subscription->user->city->name}}</td>
                            <td>{{$subscription->user->rates->avg('value')}}</td>
                            <td>{{$subscription->user->created_at}}</td>
                            <td>{{$subscription->user->order}}</td>

                            <td>
                                <a href="{{route('admin.families.show',$subscription->user)}}" class="btn btn-info btn-circle" data-original-title="عرض">
                                    <i style="padding-top:5px;padding-left: 6px;" class="fa fa-eye"></i>
                                </a>
                                <a href="{{route('admin.families.edit',$subscription->user->id)}}" class="btn btn-info btn-circle" data-original-title="تعديل">
                                    <i style="padding-top:5px;padding-left: 6px;" class="fa fa-pencil"></i>
                                </a>
                                <a href="#" onclick="Delete({{$subscription->user->id}})" data-toggle="tooltip" data-original-title="حذف" class="btn btn-danger btn-circle">
                                    <i style="padding-top: 5px;padding-left: 4px;" class="fa fa-trash-o"></i>
                                </a>
                                {!!Form::open( ['route' => ['admin.families.destroy',$subscription->user->id] ,'id'=>'delete-form'.$subscription->user->id, 'method' => 'Delete']) !!}
                                {!!Form::close() !!}
                            </td>

                        </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- #END# Exportable Table -->

@endsection

@push('scripts')
<script>
    function Delete(id) {
        var item_id = id;
        // console.log(item_id);
        Swal.fire({
            title: "هل أنت متأكد ",
            text: "هل تريد حذف هذا العضو ؟",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'موافق !',
            cancelButtonText:'الغاء'
        }).then((result) => {
            if (result.value) {
                document.getElementById('delete-form' + item_id).submit();
            }else{
                Swal.fire(
                    'تم الالغاء!',
                    'تم الغاء الحذف بنجاح !',
                    'success'
                )
            }
        });

    }

</script>
@include('dashboard.layout.datatable-scripts')
@endpush