routes/admin.php
<?php
namespace  App\Http\Controllers\Dashboard;
use App\Http\Controllers\Dashboard\Subscriptions\PlanController;
use App\Http\Controllers\Dashboard\Subscriptions\SubscriptionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});



Route::group(['as'=>'admin.','prefix'=>'dashboard/admin','middleware' => 'auth:Admin'],function (){
    Route::get('/',[IndexController::class,'index'])->name('index');
    Route::get('print/orders/{order}',[OrderController::class,'print'])->name('order.print');
    Route::resources([
        'admins'=>AdminController::class,
        'families'=>FamilyController::class,
        'categories'=>CategoryController::class,
        'sub-categories'=>SubCategoryController::class,
        'products'=>ProductController::class,
        'product-colors'=>ProductColorController::class,
        'product-sizes'=>ProductSizeController::class,
        'deliveries'=>DeliveryController::class,
        'banners'=>BannerController::class,
        'coupons'=>CouponController::class,
        'orders'=>OrderController::class,
        'users'=>UserController::class,
        'cities'=>CityController::class,
        'contacts'=>ContactController::class,
        'notifications'=>NotificationController::class,
        'roles'=>RoleController::class,
        'plans'=>PlanController::class,
        'settings'=>SettingsController::class,
        'supported-cities'=>SupportedCityController::class
    ]);
    Route::put('delivery/assign/{cart}',[DeliveryController::class,'assignOrder'])->name('delivery.assign');
    Route::get('login/{family}',[FamilyController::class,'login'])->name('families.login');
    Route::post('subscription/{family}/{type}',[SubscriptionController::class,'subscription'])->name('subscription');
    Route::post('subscription/{family}',[SubscriptionController::class,'updateSubscription'])->name('update.subscription');
    Route::get('gallery-destroy/{media}',[ProductController::class,'destroyGallery'])->name('gallery.destroy');
    Route::get('nearly-ended-subscriptions',[SubscriptionController::class,'nearlyEnded'])->name('nearlyEnded');
    Route::get('roles/{role}',[RoleController::class,'changeStatus'])->name('active.role');
    Route::get('product-size-default/{product}/{productSize}',[ProductSizeController::class,'toggleDefault'])->name('product-size-toggle');
    Route::get('rate/product',[RateController::class,'product'])->name('rate.product');
    Route::get('rate/family',[RateController::class,'family'])->name('rate.family');
    Route::get('orders/{order}/{status}',[OrderController::class,'changeStatus'])->name('order.change.status');
    Route::view('tracking','dashboard.deliveries.tracking')->name('deliveries.tracking');
});

routes/web.php
<?php

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/','dashboard.layout.login' );
//Route::view('/','landing' );

Route::get('add_family', [HomeController::class,'index'])->name('web.add_family');
Route::post('store_family', [HomeController::class,'storeFamily'])->name('web.store_family');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Http/Controllers/Api/Family/ProductController.php
<?php

namespace App\Http\Controllers\Api\Family;

use App\Http\Controllers\Controller;
use App\Http\Resources\BaseCollection;
use App\Http\Resources\Product\ProductResource;
use App\Models\Product;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use responder;

class ProductController extends Controller
{
    public function index()
    {
        return responder::success(new BaseCollection(auth()->user()->products()->withAvg('rates', 'value')->with('sizes', 'colors', 'sub_category', 'family', 'media')->paginate(15), ProductResource::class));
    }

    public function show(Product $familyProduct)
    {
        return responder::success(new ProductResource($familyProduct));
    }

    public function update(Request $request, Product $familyProduct)
    {
        $validated = $request->validate([
            'is_active' => 'required|boolean'
        ]);
        $familyProduct->update($validated);

        return responder::success('تم تعديل حالة المنتج بنجاح !');
    }


    public function storeProductByFamily(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'name' => 'required|string',
            'info' => 'required|string',
            'image' => 'required|image',
            'sub_category_id' => 'required|exists:sub_categories,id',
            'images' => 'required|array',
            'images.*' => 'required|image',
            'size_name' => 'required|string',
            'price' => 'required|numeric|min:0',
            'color_name' => 'sometimes|nullable|string',
            'color_code' => 'string|nullable',
            'is_active' => 'required|boolean'
        ]);
        DB::beginTransaction();
        $validated['family_id'] = auth()->id();
        $product = Product::create($validated);
        foreach ($request['images'] as $image) {
            $product->addMedia($image)->toMediaCollection('images');
        }
        $product->sizes()->create(['name' => $request['size_name'], 'price' => $request['price'], 'is_default' => 1]);
        if ($request->has('color_name') and $request->color_code != '#010101') {
            $product->colors()->create(['name' => $request['color_name'], 'code' => $request['color_code']]);
        }
        DB::commit();
        return \responder::success('تم اضافة المنتج بنجاح !');
    }
}

app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\BaseCollection;
use App\Http\Resources\Product\ProductResource;
use App\Models\Family;
use App\Models\Product;
use App\Traits\ApiResponse;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use responder;

class ProductController extends Controller
{
    use  ApiResponse;


    public function index()
    {
        $products=Product::query();
        $products->where('is_active',1);
        $products->whereHas('family',function ($q){
            $q->valid();
        });
        if (request('name')){
            $name=request('name');
            $products->where(function ($q) use ($name){
                $q->where('name','like',"%$name")
                    ->orWhere('name','like',"%$name%")
                    ->orWhere('name','like',"$name%");
            });
        }
        return responder::success(new BaseCollection($products->withAvg('rates','value')->with('sub_category','sizes','colors','media')->latest()->paginate(8),ProductResource::class));
    }
    public function show(Product $product)
    {
        return $this->success(new ProductResource($product));
    }

    public function ProductsByFamily(Family $family): JsonResponse
    {
        $products=Product::query();
        $products->where('family_id',$family->id)->where('is_active',1);
        if (request()->has('sub_category_id')){
            $products->where('sub_category_id',request('sub_category_id'));
        }
        return responder::success(new BaseCollection($products->withAvg('rates','value')->with('sub_category','colors','sizes','media','family')->latest()->paginate(10),ProductResource::class));
    }
}

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Admin;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;
use Spatie\Permission\Models\Role;

class AdminController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index(Request $request)
    {

        return \view('dashboard.admin.index')->with('users',Admin::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        $roles = Role::all();
        return view('dashboard.admin.add', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'name' => 'required|string',
            'password' => 'required|confirmed',
            'role_id' => 'required',
            'email' => 'required|email|unique:admins,email',
        ]);
        $user = Admin::create($validator);
        $user->assignRole(Role::find($request->input('role_id')));
        $user->syncPermissions(Role::find($request->input('role_id'))->permissions()->pluck('id'));

        toast('تم اضافة المدير بنجاح !', 'success');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Factory|View
     */
    public function edit(Admin $admin)
    {
        $userRole = $admin->roles->pluck('name', 'id')->all();
        $roles = Role::all();

        return view('dashboard.admin.edit', ['user' => $admin, 'roles' => $roles, 'userRole' => $userRole]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Admin $admin
     * @return RedirectResponse
     */
    public function update(Request $request, Admin $admin)
    {

        $validator = $request->validate([
            'name' => 'required|string',
            'password' => 'nullable|confirmed',
            'role_id' => 'required',
            'email' => 'required|email|unique:admins,email,' . $admin->id,
        ]);
        $validator = array_filter($validator, function ($value) {
            return !is_null($value) && $value !== '';
        });
        $admin->update($validator);
        DB::table('model_has_roles')->where('model_id', $admin->id)->delete();
        DB::table('model_has_permissions')->where('model_id', $admin->id)->delete();

        $admin->assignRole(Role::find($request->input('role_id')));
        $admin->syncPermissions(Role::find($request->input('role_id'))->permissions()->pluck('id'));

        toast('تم تعديل المدير بنجاح !', 'success');
        return redirect()->route('admin.admins.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Admin $admin
     * @return Response
     * @throws Exception
     */
    public function destroy(Admin $admin)
    {
        $admin->delete();
        toast('تم حذف المدير بنجاح !', 'success');
        return back();
    }
}

app/Http/Controllers/Dashboard/BannerController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Banner;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View|Response
     */
    public function index()
    {
        return view('dashboard.banners.index', ['items' => Banner::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     */
    public function create()
    {
        return view('dashboard.banners.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate(['name' => 'required|string',
            'image' => 'required|image',
            'url' => 'nullable|sometimes|url',
            'city_id'=>'nullable',
            'product_id'=>'nullable'
        ]);
        Banner::create($validated);

        toast('تم اضافة البنر بنجاح !', 'success');
        return back();

    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Banner $banner
     * @return Application|Factory|View|Response
     */
    public function edit(Banner $banner)
    {
        return view('dashboard.banners.edit', compact('banner'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Banner $banner
     * @return RedirectResponse
     */
    public function update(Request $request, Banner $banner)
    {
        $validated = $request->validate(['name' => 'required|string',
            'url' => 'nullable|sometimes|url',
            'image' => 'nullable|sometimes|image',
            'city_id'=>'nullable',
            'product_id'=>'nullable'

        ]);
        $banner->update($validated);
        toast('تم تعديل البنر بنجاح ', 'success');
        return redirect()->route('admin.banners.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Banner $banner
     * @return RedirectResponse
     */
    public function destroy(Banner $banner)
    {
        $banner->delete();
        toast('تم حذف البنر بنجاح !', 'success');
        return back();
    }
}

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return  view('dashboard.categories.index',['items'=>Category::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return  view('dashboard.categories.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
       $validated= $request->validate(['name'=>'required|string','image'=>'required|image','description'=>'required|string']);
        Category::create($validated);

        toast('تم اضافة القسم الرئيسي بنجاح !','success');
        return  back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View|Response
     */
    public function edit(Category $category)
    {
        return  view('dashboard.categories.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Category $category
     * @return RedirectResponse
     */
    public function update(Request $request, Category  $category)
    {
        $validated=$request->validate(['name'=>'required|string','image'=>'nullable|sometimes|image','description'=>'required|string']);
        $category->update($validated);
        toast('تم تعديل القسم بنجاح ','success');
        return  redirect()->route('admin.categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Category $category
     * @return RedirectResponse
     */
    public function destroy(Category  $category)
    {
        $category->delete();
        toast('تم حذف القسم بنجاح !','success');
        return back();
    }
}

app/Http/Controllers/Dashboard/ContactController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Contact;

class ContactController extends Controller
{
    //

    public function index()
    {
        return view('dashboard.contact.index')->with('contacts',Contact::orderByDesc('created_at')->get());
    }
}

resources/views/dashboard/products/actions.blade.php
<a href="{{route('admin.products.edit',$product->id)}}"
   class="btn btn-info btn-circle "
   data-original-title="تعديل">
    <i style="padding-top:5px;padding-left: 6px;" class="fa fa-pencil"></i>
</a>
<a href="#" onclick="Delete('{{$product->id}}')" class="btn btn-info btn-circle "
   data-original-title="حذف">
    <i style="padding-top:5px;padding-left: 6px;" class="fa fa-trash"></i>
</a>
{!! Form::open(['route'=>['admin.products.destroy',$product->id],'method'=>'Delete','class'=>'hidden','id'=>'delete-form'.$product->id]) !!}
{!! Form::close() !!}

resources/views/dashboard/products/add.blade.php
@extends('dashboard.layout.app')

@section('title')
إضافة  منتج
@endsection
@section('header')

@endsection

@section('content')

<!-- Basic Validation -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card animated slideInUp">
      <div class="header">
        <h2>إضافة  منتج جديد</h2>
        <ul class="header-dropdown m-r--5">
            <a href="{{route('admin.products.index')}}">   <button class="btn btn-danger">كل المنتجات </button></a>
</ul>
      </div>
      <div class="body">
          {!!Form::open( ['route' => 'admin.products.store', 'method' => 'Post','files'=>true]) !!}
            @include('dashboard.products.form')
          {!!Form::close() !!}
      </div>
    </div>
  </div>
</div>
<!-- #END# Basic Validation -->
@endsection

@section('footer')

@endsection

resources/views/dashboard/products/edit.blade.php
@extends('dashboard.layout.app')

@section('title')
    تعديل المنتج
    {{ $product->name }}
@endsection
@section('header')

@endsection

@section('content')

    <!-- Basic Validation -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card animated slideInUp">
                <div class="header">
                    <h2>تعديل المنتج {{ $product->name }}</h2>
                    <ul class="header-dropdown m-r--5">
                        <a href="{{route('admin.products.index')}}">
                            <button class="btn btn-danger">كل المنتجات</button>
                        </a>
                    </ul>
                </div>
                <div class="body">
                    {!!Form::model($product , ['route' => ['admin.products.update' , $product->id] , 'files'=>true,'method' => 'PATCH']) !!}
                    @include('dashboard.products.form')
                    {!!Form::close() !!}
                </div>
            </div>
        </div>
    </div>


    <!-- #END# Basic Validation -->
@endsection

@section('footer')

@endsection

resources/views/dashboard/products/form.blade.php
<x-text title="اسم المنتج" name="name"/>
<x-text title="وصف المنتج" name="info"/>
<x-select title="اسم الاسرة" :items="families()" name="family_id"/>
<x-select title="القسم الفرعي" :items="sub_categories()" name="sub_category_id"/>
<x-file name="image" title="الصورة الرئيسية"/>
@if (isset($product))
    <div class="form-group ">
        <label>الصورة الرئيسية: </label>
        <a href="{{$product->image}}" target="_blank"><img src="{{$product->image}}" class="img-responsive thumbnail"
                                                           style="width:100px; height:100px"></a>
    </div>
@endif
<div class="form-group ">
    <label class="form-label">صور المعرض</label>
    {!! Form::file('images[]',['class'=>'form-control','multiple'])!!}
    <div class="form-line">
    </div>
</div>
@if (isset($product))
    <div class="row clearfix">
        <label>صور المعرض: </label>
        <br>
        @foreach($product->getMedia('images') as $image)
            <div class="col-xs-1 align-center">
                <a href="{{$image->getUrl()}}" target="_blank"><img src="{{$image->getUrl()}}" class="img-responsive thumbnail" style="width:100px; height:100px"></a>
                <a href="{{route('admin.gallery.destroy',$image)}}" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a>
            </div>
        @endforeach

    </div>
@endif

@if (!isset($product))
    <x-text name="size_name" title="اسم المقاس"></x-text>
    <x-number name="price" title="السعر"></x-number>
    <x-text name="color_name" title="اسم اللون"></x-text>
    <div class="form-group form-float">
        <label class="form-label">اختار اللون</label>
        {!! Form::color('color_code','#010101',['class'=>'form-control','placeholder'=>'حدد اللون'])!!}
        <div class="form-line">
        </div>
    </div>
@endif



<button class="btn btn-primary waves-effect" type="submit">حفظ</button>

resources/views/dashboard/products/index.blade.php
@extends('dashboard.layout.app')

@section('title')
    كل  المنتجات
@endsection
@section('header')
    <link rel="stylesheet" type="text/css"
          href="https://cdn.datatables.net/v/bs/dt-1.10.18/b-1.5.6/r-2.2.2/datatables.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css
"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.5/css/responsive.dataTables.min.css
"/>
@endsection
@section('content')
    @include('validation')
    <!-- Exportable Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card animated slideInUp">
                <div class="header">
                    <h2>
                        كل المنتجات
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <a href="{{route('admin.products.create')}}">
                            <button class="btn btn-success">إضافة منتج جديد</button>
                        </a>
                    </ul>
                </div>
                <div class="body">
                    {{$dataTable->table()}}

                </div>
            </div>
        </div>
    </div>
    <!-- #END# Exportable Table -->

@endsection

@section('footer')


@include('components.yajra-datatable-scripts')

    <script>
        function Delete(id) {
            var item_id = id;
            // console.log(item_id);
            Swal.fire({
                title: "هل أنت متأكد ",
                text: "هل تريد حذف هذا المنتج ؟",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'موافق !',
                cancelButtonText: 'الغاء'
            }).then((result) => {
                if (result.value) {
                    document.getElementById('delete-form' + item_id).submit();
                } else {
                    Swal.fire(
                        'تم الالغاء!',
                        'تم الغاء الحذف بنجاح !',
                        'success'
                    )
                }
            });
        }
    </script>


@endsection